Repository strapi/design-system, pull requests merged in 2022-03, with the labels that each got.

#538 ToggleCheckbox: Improve styles to clarify the components state
  packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js
  packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.stories.mdx
  packages/strapi-design-system/src/ToggleCheckbox/__tests__/ToggleCheckbox.e2e.js
  packages/strapi-design-system/src/ToggleInput/ToggleInput.js
  packages/strapi-design-system/src/ToggleInput/ToggleInput.stories.mdx
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#559 DatePicker: allow passing in a placeholder, to fix a flaky test
  packages/strapi-design-system/src/DatePicker/DatePicker.js
  packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#553 Rename Stack size prop to spacing
  packages/strapi-design-system/src/Accordion/Accordion.js
  packages/strapi-design-system/src/Accordion/Accordion.stories.mdx
  packages/strapi-design-system/src/Accordion/AccordionToggle.js
  packages/strapi-design-system/src/Alert/Alert.stories.mdx
  packages/strapi-design-system/src/Badge/Badge.stories.mdx
  packages/strapi-design-system/src/Breadcrumbs/Breadcrumbs.stories.mdx
  packages/strapi-design-system/src/Button/Button.stories.mdx
  packages/strapi-design-system/src/Card/CardAction.js
  packages/strapi-design-system/src/CarouselInput/CarouselActions.js
  packages/strapi-design-system/src/CarouselInput/CarouselInput.js
  packages/strapi-design-system/src/Checkbox/Checkbox.js
  packages/strapi-design-system/src/Combobox/Combobox.js
  packages/strapi-design-system/src/Dialog/Dialog.stories.mdx
  packages/strapi-design-system/src/Dialog/DialogFooter.js
  packages/strapi-design-system/src/Field/Field.stories.mdx
  packages/strapi-design-system/src/FocusTrap/ExampleComponent.js
  packages/strapi-design-system/src/Link/Link.stories.mdx
  packages/strapi-design-system/src/LiveRegions/LiveRegions.stories.mdx
  packages/strapi-design-system/src/MainNav/NavSection.js
  packages/strapi-design-system/src/MainNav/NavSections.js
  packages/strapi-design-system/src/NumberInput/NumberInput.js
  packages/strapi-design-system/src/Select/Select.js
  packages/strapi-design-system/src/Select/Select.stories.mdx
  packages/strapi-design-system/src/Select/SelectList.js
  packages/strapi-design-system/src/Select/__tests__/Select.spec.js
  packages/strapi-design-system/src/Stack/Stack.js
  packages/strapi-design-system/src/Stack/Stack.stories.mdx
  packages/strapi-design-system/src/Status/Status.stories.mdx
  packages/strapi-design-system/src/SubNav/SubNavSections.js
  packages/strapi-design-system/src/TextInput/TextInput.js
  packages/strapi-design-system/src/Textarea/Textarea.js
  packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
  packages/strapi-design-system/src/ToggleInput/ToggleInput.js
  packages/strapi-design-system/src/themes/Theme.stories.mdx
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#558 SimpleMenu: remove invalid HTML attribute label
  packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap.orig
Labels: pr: enhancement

#565 DatePicker: fix onSelect event
  packages/strapi-design-system/src/DatePicker/DatePicker.js
  packages/strapi-design-system/src/DatePicker/DatePickerCalendar.js
Labels: pr: fix

#567 [Dark mode] Toggle
  packages/strapi-design-system/.storybook/components/Theme.js
  packages/strapi-design-system/.storybook/hooks/useThemeType.js
  packages/strapi-design-system/.storybook/main.js
  packages/strapi-design-system/.storybook/manager.js
  packages/strapi-design-system/.storybook/preview.js
  packages/strapi-design-system/.storybook/utils/createCustomTheme.js
  packages/strapi-design-system/package.json
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
  packages/strapi-design-system/yarn.lock
Labels: pr: enhancement

#586 [Dark mode] Memorize mode
  packages/strapi-design-system/.storybook/components/Theme.js
  packages/strapi-design-system/.storybook/hooks/useThemeType.js
  packages/strapi-design-system/.storybook/preview.js
  packages/strapi-design-system/src/Accordion/Accordion.stories.mdx
  packages/strapi-design-system/test-bundler.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: chore

#589 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: pr: doc

#579 FieldInput: Make input element cover the whole box
  packages/strapi-design-system/src/Field/FieldInput.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement
