Repository strapi/design-system, pull requests merged in 2022-04, with the labels that each got.

#585 ToggleCheckbox: improve disabled state styles and show default value
  packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#583 Flex Component: Add `gap` prop
  packages/strapi-design-system/src/Flex/Flex.js
  packages/strapi-design-system/src/Flex/FlexProps.js
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
  packages/strapi-design-system/src/Select/__tests__/Select.spec.js
  packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#597 [Dark mode] Enhancements
  .specifyrc.json
  packages/strapi-design-system/src/Avatar/Avatar.js
  packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.js
  packages/strapi-design-system/src/Button/Button.js
  packages/strapi-design-system/src/Button/__tests__/Button.e2e.js
  packages/strapi-design-system/src/Button/constants.js
  packages/strapi-design-system/src/Button/utils.js
  packages/strapi-design-system/src/FocusTrap/__tests__/FocusTrap.e2e.js
  packages/strapi-design-system/src/Layout/__tests__/HeaderLayout.e2e.js
  packages/strapi-design-system/src/Layout/__tests__/Layout.e2e.js
  packages/strapi-design-system/src/LinkButton/LinkButton.js
  packages/strapi-design-system/src/LinkButton/__tests__/LinkButton.e2e.js
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
  packages/strapi-design-system/src/Table/Table.js
  packages/strapi-design-system/src/themes/common-theme.js
  packages/strapi-design-system/src/themes/darkTheme/dark-colors.js
  packages/strapi-design-system/src/themes/darkTheme/dark-shadows.js
  packages/strapi-design-system/src/themes/darkTheme/index.js
  packages/strapi-design-system/src/themes/lightTheme/index.js
  packages/strapi-design-system/src/themes/lightTheme/light-colors.js
  packages/strapi-design-system/src/themes/lightTheme/light-shadows.js
  packages/strapi-design-system/src/v2/LinkButton/LinkButton.js
  packages/strapi-design-system/src/v2/LinkButton/__tests__/LinkButton.e2e.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#598 [Logo customization] Logo dimensions contained
  packages/strapi-design-system/src/MainNav/NavBrand.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#587 Fix/wording fixes
  website/data/pages/accessibility.mdx
  website/data/pages/colors.mdx
  website/data/pages/grid-system.mdx
  website/data/pages/iconography.mdx
  website/data/pages/principles.mdx
Labels: pr: doc

#599 Move vertical stack from Box to Flex with direction set to column
  packages/strapi-design-system/src/Select/__tests__/Select.spec.js
  packages/strapi-design-system/src/Stack/Stack.js
  packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement
