Repository strapi/design-system, pull requests merged in 2022-02, with the labels that each got.

#537 CardAsset: avoid stretching images
  lerna.json
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/Card/CardAsset.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
  packages/strapi-icons/package.json
Labels: pr: fix

#533 Add docs to the first set of components
  packages/strapi-design-system/src/Accordion/Accordion.js
  packages/strapi-design-system/src/Accordion/Accordion.stories.mdx
  packages/strapi-design-system/src/Accordion/AccordionGroup.js
  packages/strapi-design-system/src/Accordion/AccordionToggle.js
  packages/strapi-design-system/src/Alert/Alert.js
  packages/strapi-design-system/src/Alert/Alert.stories.mdx
  packages/strapi-design-system/src/Avatar/Avatar.js
  packages/strapi-design-system/src/Badge/Badge.js
  packages/strapi-design-system/src/BaseButton/BaseButton.stories.mdx
  packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.js
  packages/strapi-design-system/src/Box/BoxProps.js
Labels: pr: doc

#536 Move labelAction into the FieldLabel component
  packages/strapi-design-system/src/CarouselInput/CarouselInput.js
  packages/strapi-design-system/src/Field/Field.stories.mdx
  packages/strapi-design-system/src/Field/FieldLabel.js
  packages/strapi-design-system/src/NumberInput/NumberInput.js
  packages/strapi-design-system/src/Select/Select.js
  packages/strapi-design-system/src/Select/Select.stories.mdx
  packages/strapi-design-system/src/Select/__tests__/Select.spec.js
  packages/strapi-design-system/src/TextInput/TextInput.js
  packages/strapi-design-system/src/Textarea/Textarea.js
  packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
  packages/strapi-design-system/src/ToggleInput/ToggleInput.js
Labels: bug

#545 SimpleMenu: expose onOpen and onClose callbacks
  packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap.orig
Labels: pr: enhancement

#554 Datepicker: make min/ max date configurable and extend default range
  packages/strapi-design-system/src/DatePicker/DatePicker.js
  packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx
  packages/strapi-design-system/src/DatePicker/DatePickerCalendar.js
  packages/strapi-design-system/src/DatePicker/utils/getYears.js
  packages/strapi-design-system/src/DatePicker/utils/tests/getYears.spec.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement
