Repository strapi/design-system, pull requests merged in 2022-11, with the labels that each got.

#734 Status: Make preceding bullet configurable
  packages/strapi-design-system/src/Status/Status.js
  packages/strapi-design-system/src/Status/__tests__/Status.spec.js
Labels: pr: enhancement

#732 chore: Replace babel-jest with @swc/jest
  packages/strapi-design-system/jest.config.js
  packages/strapi-design-system/package.json
  packages/strapi-design-system/test-bundler.js
  packages/strapi-design-system/yarn.lock
  packages/strapi-icons/yarn.lock
Labels: pr: enhancement

#747 Status: Add small variant
  packages/strapi-design-system/src/Status/Status.js
  packages/strapi-design-system/src/Status/Status.stories.mdx
Labels: pr: enhancement

#740 feat: add vite to bundle
  .gitignore
  package.json
  packages/strapi-design-system/.eslintrc
  packages/strapi-design-system/.eslintrc.js
  packages/strapi-design-system/.gitignore
  packages/strapi-design-system/.npmignore
  packages/strapi-design-system/.prettierrc
  packages/strapi-design-system/.prettierrc.js
  packages/strapi-design-system/.storybook/main.cjs
  packages/strapi-design-system/babel.config.js
  packages/strapi-design-system/createIndexFiles.js
  packages/strapi-design-system/jest.config.js
  packages/strapi-design-system/package.json
  packages/strapi-design-system/playwright.config.js
  packages/strapi-design-system/src/Portal/Portal.js
  packages/strapi-design-system/vite.config.js
  packages/strapi-design-system/webpack.config.js
  packages/strapi-design-system/yarn.lock
  packages/strapi-icons/.gitignore
  packages/strapi-icons/.npmignore
  packages/strapi-icons/.prettierrc
  packages/strapi-icons/.prettierrc.js
  packages/strapi-icons/package.json
  packages/strapi-icons/vite.config.js
  packages/strapi-icons/webpack.config.js
  packages/strapi-icons/yarn.lock
  tools/copy-files.js
  yarn.lock
Labels: pr: chore

#703 Refactoring the DateTimePicker and the DatePicker and TimePicker state logic
  packages/strapi-design-system/global-setup.js
  packages/strapi-design-system/jest.config.js
  packages/strapi-design-system/playwright.config.js
  packages/strapi-design-system/src/DatePicker/DatePicker.js
  packages/strapi-design-system/src/DateTimePicker/DateTimePicker.js
  packages/strapi-design-system/src/DateTimePicker/DateTimePicker.stories.mdx
  packages/strapi-design-system/src/DateTimePicker/DateTimePickerProps.js
  packages/strapi-design-system/src/DateTimePicker/__tests__/DateTimePicker.e2e.js
  packages/strapi-design-system/src/DateTimePicker/__tests__/DateTimePicker.spec.js
  packages/strapi-design-system/src/DateTimePicker/__tests__/__snapshots__/DateTimePicker.spec.js.snap
  packages/strapi-design-system/src/DateTimePicker/__tests__/parseDate.test.js
  packages/strapi-design-system/src/DateTimePicker/index.js
  packages/strapi-design-system/src/DateTimePicker/parseDate.js
  packages/strapi-design-system/src/Field/Field.js
  packages/strapi-design-system/src/Field/FieldError.js
  packages/strapi-design-system/src/Select/Select.js
  packages/strapi-design-system/src/Select/Select.stories.mdx
  packages/strapi-design-system/src/Select/__tests__/Select.spec.js
  packages/strapi-design-system/src/TextInput/TextInput.js
  packages/strapi-design-system/src/TimePicker/TimePicker.js
  packages/strapi-design-system/src/TimePicker/TimePicker.stories.mdx
  packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
  packages/strapi-design-system/src/index.js
  packages/strapi-design-system/yarn.lock
Labels: pr: feature

#753 fix: dismissible layer closing prematurely
  packages/strapi-design-system/src/DismissibleLayer/DismissibleLayer.js
Labels: pr: fix

#755 BaseCheckbox: Wrap component into Box to isolate style resets
  packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.js
Labels: pr: fix

#751 fix: releases
  package.json
  packages/strapi-design-system/.npmignore
  packages/strapi-icons/.npmignore
Labels: pr: chore

#746 [enhancement]: IconButton
  packages/strapi-design-system/.eslintrc.js
  packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.stories.mdx
  packages/strapi-design-system/src/Checkbox/Checkbox.stories.mdx
  packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.js
  packages/strapi-design-system/src/DismissibleLayer/__test__/DimissibleLayer.spec.js
  packages/strapi-design-system/src/IconButton/IconButton.js
  packages/strapi-design-system/src/IconButton/IconButton.stories.mdx
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
  packages/strapi-design-system/src/Status/Status.stories.mdx
  packages/strapi-design-system/src/Switch/Switch.stories.mdx
Labels: pr: enhancement

#728 chore: use yaml templates for issue forms & add feature form
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/rfc.yml
Labels: pr: chore

#758 Button: Unify component height with the UI Kit
  packages/strapi-design-system/src/Button/Button.js
  packages/strapi-design-system/src/Button/Button.stories.mdx
  packages/strapi-design-system/src/Button/constants.js
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
  packages/strapi-design-system/src/themes/sizes.js
Labels: pr: fix

#766 Chore: Update WYSIWYG icons
  packages/strapi-icons/assets/icons/Bold.svg
  packages/strapi-icons/assets/icons/BulletList.svg
  packages/strapi-icons/assets/icons/Code.svg
  packages/strapi-icons/assets/icons/Collapse.svg
  packages/strapi-icons/assets/icons/Expand.svg
  packages/strapi-icons/assets/icons/IndentDecrease.svg
  packages/strapi-icons/assets/icons/IndentIncrease.svg
  packages/strapi-icons/assets/icons/Italic.svg
  packages/strapi-icons/assets/icons/More.svg
  packages/strapi-icons/assets/icons/NumberList.svg
  packages/strapi-icons/assets/icons/Picture.svg
  packages/strapi-icons/assets/icons/Quote.svg
  packages/strapi-icons/assets/icons/StrikeThrough.svg
  packages/strapi-icons/assets/icons/Underline.svg
Labels: pr: fix

#769 ProgressBar: Refactor component to use Box as base
  packages/strapi-design-system/src/ProgressBar/ProgressBar.js
  packages/strapi-design-system/src/ProgressBar/ProgressBar.stories.mdx
Labels: pr: enhancement

#777 chore: give the design-system website a little love
  website/.babelrc
  website/babel.config.js
  website/components/BottomNavigation/index.js
  website/components/Layout/index.js
  website/components/NavSection/index.js
  website/components/Navbar/index.js
  website/components/StyledLink/index.js
  website/next.config.js
  website/package.json
  website/pages/_document.js
  website/pages/index.js
  website/yarn.lock
Labels: pr: chore

#772 Add icons for upload view toggle
  packages/strapi-icons/assets/icons/Grid.svg
  packages/strapi-icons/assets/icons/List.svg
Labels: pr: enhancement

#778 Introduce Vite bundling
  .gitignore
  README.md
  lerna.json
  package.json
  packages/strapi-design-system/.eslintrc
  packages/strapi-design-system/.eslintrc.js
  packages/strapi-design-system/.gitignore
  packages/strapi-design-system/.npmignore
  packages/strapi-design-system/.prettierrc
  packages/strapi-design-system/.prettierrc.js
  packages/strapi-design-system/.storybook/main.cjs
  packages/strapi-design-system/babel.config.js
  packages/strapi-design-system/createIndexFiles.js
  packages/strapi-design-system/jest.config.js
  packages/strapi-design-system/package.json
  packages/strapi-design-system/playwright.config.js
  packages/strapi-design-system/src/Portal/Portal.js
  packages/strapi-design-system/vite.config.js
  packages/strapi-design-system/webpack.config.js
  packages/strapi-design-system/yarn.lock
  packages/strapi-icons/.gitignore
  packages/strapi-icons/.npmignore
  packages/strapi-icons/.prettierrc
  packages/strapi-icons/.prettierrc.js
  packages/strapi-icons/package.json
  packages/strapi-icons/vite.config.js
  packages/strapi-icons/webpack.config.js
  packages/strapi-icons/yarn.lock
  templates/component.hbs
  templates/e2e-test.hbs
  templates/root.hbs
  templates/stories.hbs
  templates/unit-test.hbs
  tools/copy-files.js
  tools/excludedFolders.js
  yarn.lock
Labels: pr: chore

#770 Badge: Update colors and height according to the UI kit
  packages/strapi-design-system/src/Badge/Badge.js
  packages/strapi-design-system/src/Badge/Badge.stories.mdx
  packages/strapi-design-system/src/themes/sizes.js
Labels: pr: fix

#773 [NumberInput]: use useControllableState to handle number vs string inputs.
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/NumberInput/NumberInput.js
  packages/strapi-design-system/src/hooks/useControllableState.js
  packages/strapi-design-system/yarn.lock
Labels: pr: fix

#785 chore: remove side-effects from package.json
  packages/strapi-design-system/package.json
  packages/strapi-icons/package.json
Labels: pr: chore

#784 [RawTable]: fix keyboard navigation when rows are updated & anchor tags
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/RawTable/RawCell.js
  packages/strapi-design-system/src/Table/Table.stories.mdx
  packages/strapi-design-system/yarn.lock
Labels: pr: fix

#788 [imports]: don't use duplicate imports as the application breaks
  packages/strapi-design-system/src/index.js
Labels: pr: fix
