Repository strapi/design-system, pull requests merged in 2022-09, with the labels that each got.

#698 NumberInput: Fix value assignment during focus
  packages/strapi-design-system/src/NumberInput/NumberInput.js
Labels: pr: fix

#700 [Fix] Document button color tokens to sroy
  packages/strapi-design-system/src/themes/Theme.stories.mdx
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: doc

#704 Fix Breadcrumb with one Crumb
  packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.js
  packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.stories.mdx
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#687 NumberInput: Allow to pass in a locale for improved number formatting
  packages/strapi-design-system/src/Link/Link.stories.mdx
  packages/strapi-design-system/src/NumberInput/NumberInput.js
  packages/strapi-design-system/src/NumberInput/NumberInput.stories.mdx
  packages/strapi-design-system/src/SubNav/SubNav.stories.mdx
  packages/strapi-design-system/src/themes/Theme.stories.mdx
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#688 DatePicker: Allow to pass in a locale
  packages/strapi-design-system/src/DatePicker/DatePicker.js
  packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx
  packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.js
  packages/strapi-design-system/src/DatePicker/utils/formatDate.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#705 Releasing 1.2.4
  lerna.json
  packages/strapi-design-system/package.json
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
  packages/strapi-icons/package.json
Labels: pr: chore

#702 [KeyboardNavigable & RawTable]: fix keyboard navigation on child elements
  packages/strapi-design-system/src/Accordion/Accordion.stories.mdx
  packages/strapi-design-system/src/KeyboardNavigable/KeyboardNavigable.js
  packages/strapi-design-system/src/RawTable/RawCell.js
  packages/strapi-design-system/src/RawTable/RawTable.js
  packages/strapi-design-system/src/RawTable/RawTable.stories.mdx
  packages/strapi-design-system/src/RawTable/RawTableContext.js
  packages/strapi-design-system/src/RawTable/RawTbody.js
  packages/strapi-design-system/src/RawTable/RawThead.js
  packages/strapi-design-system/src/RawTable/RawTr.js
  packages/strapi-design-system/src/RawTable/__tests__/RawTable.e2e.js
  packages/strapi-design-system/src/helpers/getFocusableNodes.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix, pr: enhancement

#699 [Popover]: fix position function by using @floating-ui
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/Popover/Popover.js
  packages/strapi-design-system/src/Popover/Popover.stories.mdx
  packages/strapi-design-system/src/Popover/__tests__/Popover.e2e.js
  packages/strapi-design-system/src/Popover/__tests__/Popover.spec.js
  packages/strapi-design-system/src/Select/__tests__/Select.spec.js
  packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
  packages/strapi-design-system/src/helpers/useResizeObserver.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
  packages/strapi-design-system/yarn.lock
Labels: pr: fix

#708 Fix Breadcrumb with conditional links
  packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.js
  packages/strapi-design-system/src/v2/Breadcrumbs/__tests__/Breadcrumbs.spec.js
Labels: pr: fix

#706 Adds the missing forum link
  website/components/Navbar/index.js
Labels: pr: fix
