Repository strapi/design-system, pull requests merged in 2022-08, with the labels that each got.

#668 Subnav (v2): Improve styling of child links
  packages/strapi-design-system/src/v2/SubNav/SubNav.stories.mdx
  packages/strapi-design-system/src/v2/SubNav/SubNavLink.js
  packages/strapi-design-system/src/v2/SubNav/SubNavLinkSection.js
  packages/strapi-design-system/src/v2/SubNav/SubNavSection.js
  packages/strapi-design-system/src/v2/SubNav/SubNavSectionLabel.js
  packages/strapi-design-system/src/v2/SubNav/SubNavSections.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#669 Releasing 1.2.1
  lerna.json
  packages/strapi-design-system/package.json
  packages/strapi-icons/package.json
Labels: pr: chore

#675 [Fix] Link font
  packages/strapi-design-system/src/Link/Link.js
  packages/strapi-design-system/src/v2/Link/Link.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#676 Combobox filtering behavior
  packages/strapi-design-system/src/Combobox/__tests__/utils.spec.js
  packages/strapi-design-system/src/Combobox/utils.js
Labels: pr: enhancement

#680 Update Grid, Link, and Theme documentation of the Design System
  packages/strapi-design-system/src/Grid/Grid.stories.mdx
  packages/strapi-design-system/src/Link/Link.stories.mdx
  packages/strapi-design-system/src/themes/Theme.stories.mdx
Labels: pr: doc

#677 chore: Update many children prop-types from string to node
  packages/strapi-design-system/src/Alert/Alert.js
  packages/strapi-design-system/src/Avatar/Avatar.js
  packages/strapi-design-system/src/Breadcrumbs/Breadcrumbs.js
  packages/strapi-design-system/src/Card/CardTimer.js
  packages/strapi-design-system/src/Checkbox/Checkbox.js
  packages/strapi-design-system/src/LinkButton/LinkButton.js
  packages/strapi-design-system/src/Loader/Loader.js
  packages/strapi-design-system/src/MainNav/NavLink.js
  packages/strapi-design-system/src/ProgressBar/ProgressBar.js
  packages/strapi-design-system/src/Radio/Radio.js
  packages/strapi-design-system/src/Searchbar/Searchbar.js
  packages/strapi-design-system/src/Tag/Tag.js
  packages/strapi-design-system/src/v2/Breadcrumbs/Crumb.js
  packages/strapi-design-system/src/v2/Breadcrumbs/CrumbLink.js
  packages/strapi-design-system/src/v2/LinkButton/LinkButton.js
Labels: pr: fix

#683 NumberInput: Keep scientific numbers after blur/ focus as value
  packages/strapi-design-system/src/NumberInput/NumberInput.js
  packages/strapi-design-system/src/NumberInput/__tests__/NumberInput.e2e.js
Labels: pr: fix

#685 Popover: Fix onReachEnd callback
  packages/strapi-design-system/src/Popover/Popover.js
  packages/strapi-design-system/src/helpers/useIntersection.js
Labels: pr: fix

#682 ToggleInput: Remove clear button, if the field is disabled
  packages/strapi-design-system/src/ToggleInput/ToggleInput.js
  packages/strapi-design-system/src/ToggleInput/ToggleInput.stories.mdx
  packages/strapi-design-system/src/ToggleInput/__tests__/ToggleInput.e2e.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#684 Relax hint prop-types from string to node
  packages/strapi-design-system/src/CarouselInput/Carousel.js
  packages/strapi-design-system/src/CarouselInput/CarouselInput.js
  packages/strapi-design-system/src/Checkbox/Checkbox.js
  packages/strapi-design-system/src/Combobox/Combobox.js
  packages/strapi-design-system/src/Field/Field.js
  packages/strapi-design-system/src/NumberInput/NumberInput.js
  packages/strapi-design-system/src/Select/Select.js
  packages/strapi-design-system/src/TextInput/TextInput.js
  packages/strapi-design-system/src/Textarea/Textarea.js
  packages/strapi-design-system/src/TimePicker/TimePicker.js
  packages/strapi-design-system/src/ToggleInput/ToggleInput.js
Labels: pr: enhancement
