Repository strapi/design-system, pull requests merged in 2022-06, with the labels that each got.

#615 Design guidelines to build a form added to the Grid page
  website/data/pages/grid-system.mdx
  website/public/grid-form.png
Labels: pr: enhancement

#620 Fixing @strapi/icons peer dependency in design system
  packages/strapi-design-system/package.json
Labels: pr: fix

#623 ModalBody: Decrease horizontal paddings
  packages/strapi-design-system/src/ModalLayout/ModalBody.js
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
Labels: pr: fix

#630 DS: Fix global apple system font-family
  packages/strapi-design-system/src/ThemeProvider/ThemeProvider.js
Labels: pr: fix, source: core:admin

#631 Releasing 1.2.0
  lerna.json
  packages/strapi-design-system/package.json
  packages/strapi-icons/package.json
Labels: pr: chore
