Repository strapi/design-system, pull requests merged in 2022-07, with the labels that each got.

#636 Add MIT license file
  LICENSE
  packages/strapi-design-system/LICENSE
  packages/strapi-icons/LICENSE
Labels: pr: chore

#626 chore(eslint): add eslint-mdx package and fix eslint errors
  packages/strapi-design-system/.eslintrc.js
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/Alert/Alert.stories.mdx
  packages/strapi-design-system/src/Badge/Badge.stories.mdx
  packages/strapi-design-system/src/BaseRadio/BaseRadio.stories.mdx
  packages/strapi-design-system/src/Breadcrumbs/Breadcrumbs.stories.mdx
  packages/strapi-design-system/src/Button/Button.stories.mdx
  packages/strapi-design-system/src/Card/Card.stories.mdx
  packages/strapi-design-system/src/Combobox/Combobox.stories.mdx
  packages/strapi-design-system/src/Dialog/Dialog.stories.mdx
  packages/strapi-design-system/src/Field/Field.stories.mdx
  packages/strapi-design-system/src/Grid/Grid.stories.mdx
  packages/strapi-design-system/src/Layout/HeaderLayout.stories.mdx
  packages/strapi-design-system/src/Layout/Layout.stories.mdx
  packages/strapi-design-system/src/Layout/TwoColsLayout.stories.mdx
  packages/strapi-design-system/src/Link/Link.stories.mdx
  packages/strapi-design-system/src/LiveRegions/LiveRegions.stories.mdx
  packages/strapi-design-system/src/Loader/Loader.stories.mdx
  packages/strapi-design-system/src/MainNav/MainNav.stories.mdx
  packages/strapi-design-system/src/ModalLayout/ModalLayout.stories.mdx
  packages/strapi-design-system/src/Popover/Popover.stories.mdx
  packages/strapi-design-system/src/ProgressBar/ProgressBar.stories.mdx
  packages/strapi-design-system/src/Radio/Radio.stories.mdx
  packages/strapi-design-system/src/RawTable/RawTable.stories.mdx
  packages/strapi-design-system/src/SubNav/SubNav.stories.mdx
  packages/strapi-design-system/src/Switch/Switch.stories.mdx
  packages/strapi-design-system/src/Tabs/Tabs.stories.mdx
  packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.stories.mdx
  packages/strapi-design-system/src/Tooltip/Tooltip.stories.mdx
  packages/strapi-design-system/src/Typography/Typography.stories.mdx
  packages/strapi-design-system/src/v2/Link/Link.stories.mdx
  packages/strapi-design-system/src/v2/MainNav/MainNav.stories.mdx
  packages/strapi-design-system/src/v2/SubNav/SubNav.stories.mdx
  packages/strapi-design-system/yarn.lock
Labels: pr: chore

#652 Accordion: Make height of AccordionToggle flexbile and add title ellipsis
  packages/strapi-design-system/src/Accordion/AccordionToggle.js
  packages/strapi-design-system/src/Flex/Flex.js
  packages/strapi-design-system/src/Flex/FlexProps.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#649 Fix e2e:watch command using chokidar-cli
  package.json
  packages/strapi-design-system/package.json
  yarn.lock
Labels: pr: fix

#641 NumberInput: Fix maximum significant digits which are displayed
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/NumberInput/NumberInput.js
  packages/strapi-design-system/src/NumberInput/NumberInput.stories.mdx
  packages/strapi-design-system/src/NumberInput/__tests__/NumberInput.e2e.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#653 Breadcrumbs: Implement v2 version
  packages/strapi-design-system/src/Breadcrumbs/Breadcrumbs.js
  packages/strapi-design-system/src/Layout/HeaderLayout.js
  packages/strapi-design-system/src/Layout/HeaderLayout.stories.mdx
  packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.js
  packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.stories.mdx
  packages/strapi-design-system/src/v2/Breadcrumbs/Crumb.js
  packages/strapi-design-system/src/v2/Breadcrumbs/CrumbLink.js
  packages/strapi-design-system/src/v2/Breadcrumbs/CrumbSimpleMenu.js
  packages/strapi-design-system/src/v2/Breadcrumbs/Divider.js
  packages/strapi-design-system/src/v2/Breadcrumbs/__tests__/Breadcrumbs.e2e.js
  packages/strapi-design-system/src/v2/Breadcrumbs/index.js
  packages/strapi-design-system/src/v2/index.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#635 Add indentation styling to SubNavLinkSection child elements
  packages/strapi-design-system/src/SubNav/SubNav.stories.mdx
  packages/strapi-design-system/src/SubNav/SubNavLink.js
  packages/strapi-design-system/src/SubNav/SubNavLinkSection.js
  packages/strapi-design-system/src/SubNav/SubNavSection.js
  packages/strapi-design-system/src/SubNav/SubNavSectionLabel.js
  packages/strapi-design-system/src/SubNav/SubNavSections.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#647 Docs: Update e2e test setup
  CONTRIBUTING.md
Labels: pr: doc

#657 Breadcrumbs: Update interaction colors
  packages/strapi-design-system/src/v2/Breadcrumbs/CrumbLink.js
  packages/strapi-design-system/src/v2/Breadcrumbs/CrumbSimpleMenu.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#664 DatePicker: remove default placeholder value
  packages/strapi-design-system/src/DatePicker/DatePicker.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement

#666 [Fix] Avatar img resizing
  packages/strapi-design-system/src/Avatar/Avatar.js
  packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: enhancement
