Repository strapi/design-system, pull requests merged in 2022-10, with the labels that each got.

#709 Add placement props to Popover component
  packages/strapi-design-system/src/Popover/Popover.js
  packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js
  packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.js
Labels: pr: enhancement

#712 fix: link active & hover not affecting Typography
  packages/strapi-design-system/src/Link/Link.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix

#710 Releasing 1.2.5
  lerna.json
  packages/strapi-design-system/package.json
  packages/strapi-icons/package.json
Labels: pr: chore

#717 fix: set z-index on Label to avoid z-index breaking out of parent
  packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix, source: core:content-manager

#720 [fix][ToggleCheckbox]: responsive behaviour
  packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js
  packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.stories.mdx
  packages/strapi-design-system/src/ToggleInput/ToggleInput.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix, severity: medium, source: core:content-manager

#711 [fix][Modal | Dialog]: Add dismissible layer component
  packages/strapi-design-system/src/Dialog/Dialog.js
  packages/strapi-design-system/src/DismissibleLayer/DismissibleLayer.js
  packages/strapi-design-system/src/DismissibleLayer/DismissibleLayer.stories.mdx
  packages/strapi-design-system/src/DismissibleLayer/__test__/DimissibleLayer.spec.js
  packages/strapi-design-system/src/DismissibleLayer/index.js
  packages/strapi-design-system/src/FocusTrap/FocusTrap.js
  packages/strapi-design-system/src/ModalLayout/ModalLayout.js
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
  packages/strapi-design-system/src/index.js
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: fix, severity: medium

#716 Cleaning and/or solving the frontend tests (warning/logs)
  packages/strapi-design-system/src/DatePicker/DatePickerCalendar.js
  packages/strapi-design-system/src/Icon/Icon.stories.mdx
  packages/strapi-design-system/src/Link/Link.stories.mdx
  packages/strapi-design-system/src/SimpleMenu/SimpleMenu.stories.mdx
  packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.stories.mdx
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
  website/.lintstagedrc.js
  website/components/Navbar/index.js
Labels: pr: chore

#729 Fix theme colors stories
  packages/strapi-design-system/src/themes/ColorButton.js
  packages/strapi-design-system/src/themes/Theme.stories.mdx
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Labels: pr: doc

#730 Remove storyshots
  packages/strapi-design-system/package.json
  packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
  packages/strapi-design-system/tests/storyshots.spec.js
  packages/strapi-design-system/yarn.lock
Labels: pr: chore

#731 Upgrade jest-* to 29.x
  package.json
  packages/strapi-design-system/jest.config.js
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
  packages/strapi-design-system/src/themes/__tests__/extendTheme.spec.js
  packages/strapi-design-system/yarn.lock
  packages/strapi-icons/package.json
Labels: pr: chore

#726 Icon: Update Strapi logo icon
  packages/strapi-icons/assets/icons/Strapi.svg
Labels: pr: chore

#737 Jest: Respect os specific files for the check-exports test
  packages/strapi-design-system/tests/check-exports.spec.js
  packages/strapi-design-system/tests/filesToKeep.js
Labels: pr: fix
