Repository strapi/design-system, pull requests merged in 2023-01, with the labels that each got.

#821 [fix] Bold & BulletList svg viewbox
  packages/strapi-icons/assets/icons/Bold.svg
  packages/strapi-icons/assets/icons/BulletList.svg
Labels: pr: fix

#824 [fix] minDate not working for DatePicker component
  packages/strapi-design-system/src/DatePicker/DatePicker.js
  packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.e2e.js
Labels: pr: fix

#834 Chore: Remove @specifyapp/cli as a dependency
  CONTRIBUTING.md
  package.json
  yarn.lock
Labels: pr: chore

#835 [enh] Initials customization
  packages/strapi-design-system/src/Avatar/Avatar.js
  packages/strapi-design-system/src/Avatar/Avatar.stories.mdx
Labels: pr: enhancement

#828 chore: use esnext
  packages/strapi-design-system/vite.config.js
  packages/strapi-icons/vite.config.js
Labels: pr: chore

#842 [fix] MainNav scrollable
  packages/strapi-design-system/src/Divider/Divider.js
  packages/strapi-design-system/src/MainNav/MainNav.js
  packages/strapi-design-system/src/MainNav/MainNav.stories.mdx
  packages/strapi-design-system/src/MainNav/NavFooter.js
  packages/strapi-design-system/src/MainNav/NavLink.js
  packages/strapi-design-system/src/MainNav/NavSections.js
  packages/strapi-design-system/src/MainNav/NavUser.js
  packages/strapi-design-system/src/MainNav/index.js
  packages/strapi-design-system/src/v2/MainNav/MainNav.js
  packages/strapi-design-system/src/v2/MainNav/MainNav.stories.mdx
  packages/strapi-design-system/src/v2/MainNav/NavFooter.js
  packages/strapi-design-system/src/v2/MainNav/NavLink.js
  packages/strapi-design-system/src/v2/MainNav/NavSections.js
  packages/strapi-design-system/src/v2/MainNav/NavUser.js
  packages/strapi-design-system/src/v2/MainNav/index.js
Labels: pr: fix

#847 [enh] Update Avatar size
  packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.js
  packages/strapi-design-system/src/Avatar/constants.js
Labels: pr: enhancement, source: design-system

#849 chore: add onReachEnd popover callback to SimpleMenu v2 component
  packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.js
Labels: pr: chore

#854 [feature] add json input
  docs/stories/JSONInput.stories.mdx
  docs/yarn.lock
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/JSONInput/JSONInput.js
  packages/strapi-design-system/src/JSONInput/JSONInputContainer.js
  packages/strapi-design-system/src/JSONInput/__tests__/JSONInput.e2e.js
  packages/strapi-design-system/src/JSONInput/__tests__/JSONInput.spec.js
  packages/strapi-design-system/src/JSONInput/index.js
  packages/strapi-design-system/src/JSONInput/utils/decorationExtension.js
  packages/strapi-design-system/src/index.ts
  packages/strapi-design-system/yarn.lock
Labels: pr: feature, source: design-system

#856 [Release]: 1.6.0
  .prettierignore
  docs/package.json
  lerna.json
  packages/strapi-design-system/package.json
  packages/strapi-icons/package.json
Labels: pr: chore

#859 [Lerna]: handle parallel with storybook
  .github/workflows/bundle-size.yml
  docs/.storybook/main.js
  lerna.json
  package.json
  yarn.lock
Labels: pr: chore

#864 [fix] Inputs hint accessibility
  packages/strapi-design-system/src/Combobox/Combobox.js
  packages/strapi-design-system/src/DateTimePicker/DateTimePicker.js
  packages/strapi-design-system/src/DateTimePicker/__tests__/__snapshots__/DateTimePicker.spec.js.snap
  packages/strapi-design-system/src/Field/FieldHint.js
  packages/strapi-design-system/src/Select/Select.js
  packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js
Labels: pr: fix

#866 fix/workflows
  .github/workflows/tests.yml
  packages/strapi-design-system/src/DateTimePicker/__tests__/__snapshots__/DateTimePicker.spec.js.snap
Labels: pr: chore

#853 [chore] Remove prefix usage in useId
  packages/strapi-design-system/src/Accordion/Accordion.tsx
  packages/strapi-design-system/src/BaseRadio/BaseRadio.tsx
  packages/strapi-design-system/src/Card/Card.tsx
  packages/strapi-design-system/src/CarouselInput/CarouselInput.js
  packages/strapi-design-system/src/Checkbox/Checkbox.js
  packages/strapi-design-system/src/Combobox/Combobox.js
  packages/strapi-design-system/src/Combobox/__tests__/Combobox.e2e.js
  packages/strapi-design-system/src/DateTimePicker/DateTimePicker.js
  packages/strapi-design-system/src/DateTimePicker/__tests__/DateTimePicker.e2e.js
  packages/strapi-design-system/src/DateTimePicker/__tests__/__snapshots__/DateTimePicker.spec.js.snap
  packages/strapi-design-system/src/Dialog/Dialog.js
  packages/strapi-design-system/src/Field/Field.js
  packages/strapi-design-system/src/NumberInput/NumberInput.js
  packages/strapi-design-system/src/Select/Select.js
  packages/strapi-design-system/src/Select/__tests__/Select.spec.js
  packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js
  packages/strapi-design-system/src/SubNav/SubNavHeader.js
  packages/strapi-design-system/src/SubNav/SubNavLinkSection.js
  packages/strapi-design-system/src/SubNav/SubNavSection.js
  packages/strapi-design-system/src/Tabs/TabGroup.js
  packages/strapi-design-system/src/TextInput/TextInput.js
  packages/strapi-design-system/src/Textarea/Textarea.js
  packages/strapi-design-system/src/TimePicker/TimePicker.js
  packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
  packages/strapi-design-system/src/ToggleInput/ToggleInput.js
  packages/strapi-design-system/src/ToggleInput/__tests__/ToggleInput.e2e.js
  packages/strapi-design-system/src/Tooltip/Tooltip.js
  packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.js
  packages/strapi-design-system/src/helpers/__tests__/useId.spec.tsx
  packages/strapi-design-system/src/helpers/genId.ts
  packages/strapi-design-system/src/helpers/useId.ts
  packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.js
  packages/strapi-design-system/src/v2/SubNav/SubNavHeader.js
  packages/strapi-design-system/src/v2/SubNav/SubNavLinkSection.js
  packages/strapi-design-system/src/v2/SubNav/SubNavSection.js
Labels: pr: chore

#869 Bump lerna, fix HMR with Storybook & fix workflow running twice
  .github/workflows/tests.yml
  nx.json
  package.json
  packages/strapi-design-system/package.json
  packages/strapi-design-system/vite.config.ts
  packages/strapi-icons/package.json
  yarn.lock
Labels: pr: chore

#872 workflows not running but are required
  .github/workflows/tests.yml
Labels: pr: fix
