Repository strapi/design-system, pull requests merged in 2023-02, with the labels that each got.

#836 [chore] Add connecting to Strapi section to CONTRIBUTING
  CONTRIBUTING.md
Labels: pr: chore, source: design-system

#875 [chore] update contributing
  CONTRIBUTING.md
Labels: pr: doc

#871 [fix] Remove component with unnecessary computeScrollIntoView
  packages/strapi-design-system/src/Combobox/Combobox.js
  packages/strapi-design-system/src/Combobox/ComboboxList.js
Labels: pr: fix

#877 [fix] Focus the editor when clicking the label
  packages/strapi-design-system/src/JSONInput/JSONInput.js
Labels: pr: fix

#885 Fix missing proptype validation
  packages/strapi-design-system/src/Field/Field.js
  packages/strapi-design-system/src/Select/Select.js
  packages/strapi-design-system/src/TextInput/TextInput.js
  packages/strapi-design-system/src/TimePicker/TimePicker.js
Labels: pr: fix, source: design-system

#894 Migrate JSONInput to TypeScript
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/Button/constants.ts
  packages/strapi-design-system/src/JSONInput/JSONInput.tsx
  packages/strapi-design-system/src/JSONInput/JSONInputContainer.tsx
  packages/strapi-design-system/src/JSONInput/index.ts
  packages/strapi-design-system/src/LinkButton/LinkButton.tsx
  packages/strapi-design-system/src/Typography/Typography.tsx
  packages/strapi-design-system/src/Typography/utils.ts
  yarn.lock
Labels: pr: chore

#896 LinkButton(v2): Convert component to use Typescript
  packages/strapi-design-system/src/v2/LinkButton/LinkButton.tsx
  packages/strapi-design-system/src/v2/LinkButton/index.ts
Labels: pr: enhancement

#898 [fix] IconButton no border
  packages/strapi-design-system/src/Box/Box.tsx
Labels: pr: fix

#900 Add deprecate notice to v1 components
  docs/components/DeprecationNotice.js
  docs/stories/Breadcrumbs.stories.mdx
  docs/stories/Link.stories.mdx
  docs/stories/LinkButton.stories.mdx
  docs/stories/MainNav.stories.mdx
  docs/stories/Pagination.stories.mdx
  docs/stories/SimpleMenu.stories.mdx
  docs/stories/Stack.stories.mdx
  docs/stories/SubNav.stories.mdx
  docs/stories/v2/MainNav.stories.mdx
Labels: pr: doc
