Repository strapi/design-system, pull requests merged in 2023-07, with the labels that each got.

#1172 fix: date picker with some timezones would change date automatically
  package.json
  packages/strapi-design-system/src/DatePicker/DatePicker.tsx
  packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.tsx
  test/env-setup.js
  yarn.lock
Labels: pr: fix, source: design-system

#1169 [release]: 1.8.1
  lerna.json
  package.json
  packages/primitives/package.json
  packages/primitives/src/components/Collection/Collection.tsx
  packages/primitives/src/components/Combobox/Combobox.tsx
  packages/primitives/src/components/Select/Select.tsx
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/Button/Button.tsx
  packages/strapi-design-system/src/Combobox/Combobox.tsx
  packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx
  packages/strapi-design-system/src/DatePicker/DatePicker.tsx
  packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.tsx
  packages/strapi-design-system/src/DateTimePicker/DateTimePicker.tsx
  packages/strapi-design-system/src/Grid/Grid.tsx
  packages/strapi-design-system/src/Grid/__tests__/Grid.e2e.ts
  packages/strapi-design-system/src/MainNav/MainNav.tsx
  packages/strapi-design-system/src/MainNav/MainNavContext.tsx
  packages/strapi-design-system/src/MainNav/NavBrand.tsx
  packages/strapi-design-system/src/MainNav/NavCondense.tsx
  packages/strapi-design-system/src/MainNav/NavFooter.js
  packages/strapi-design-system/src/MainNav/NavFooter.tsx
  packages/strapi-design-system/src/MainNav/NavLink.tsx
  packages/strapi-design-system/src/MainNav/NavSection.tsx
  packages/strapi-design-system/src/MainNav/NavSections.tsx
  packages/strapi-design-system/src/MainNav/NavUser.js
  packages/strapi-design-system/src/MainNav/NavUser.tsx
  packages/strapi-design-system/src/MainNav/index.ts
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.tsx
  packages/strapi-design-system/src/ProgressBar/__tests__/ProgressBar.e2e.ts
  packages/strapi-design-system/src/Radio/__tests__/Radio.e2e.ts
  packages/strapi-design-system/src/Radio/__tests__/Radio.spec.tsx
  packages/strapi-design-system/src/SimpleMenu/SimpleMenu.tsx
  packages/strapi-design-system/src/SimpleMenu/__tests__/SimpleMenu.spec.tsx
  packages/strapi-design-system/src/SimpleMenu/index.ts
  packages/strapi-design-system/src/SimpleMenu/utils.ts
  packages/strapi-design-system/src/SubNav/SubNav.tsx
  packages/strapi-design-system/src/SubNav/SubNavHeader.tsx
  packages/strapi-design-system/src/SubNav/SubNavLink.tsx
  packages/strapi-design-system/src/SubNav/SubNavLinkSection.tsx
  packages/strapi-design-system/src/SubNav/SubNavSection.tsx
  packages/strapi-design-system/src/SubNav/SubNavSectionLabel.tsx
  packages/strapi-design-system/src/SubNav/SubNavSections.tsx
  packages/strapi-design-system/src/SubNav/index.ts
  packages/strapi-design-system/src/Tabs/__tests__/Tabs.e2e.ts
  packages/strapi-design-system/src/ToggleCheckbox/__tests__/ToggleCheckbox.e2e.ts
  packages/strapi-design-system/src/ToggleInput/__tests__/ToggleInput.e2e.ts
  packages/strapi-design-system/src/Tooltip/Tooltip.tsx
  packages/strapi-design-system/src/v2/Breadcrumbs/CrumbSimpleMenu.tsx
  packages/strapi-design-system/src/v2/SimpleMenu/Menu.tsx
  packages/strapi-design-system/src/v2/index.ts
  packages/strapi-design-system/test/utils.tsx
  packages/strapi-icons/package.json
  test/env-setup.js
  yarn.lock
Labels: source: release, pr: release

#1179 fix: make label an optional prop
  packages/strapi-design-system/src/Combobox/Combobox.tsx
  packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx
  packages/strapi-design-system/src/Select/MultiSelect.tsx
  packages/strapi-design-system/src/Select/MultiSelectNested.tsx
  packages/strapi-design-system/src/Select/SingleSelect.tsx
  packages/strapi-design-system/src/Select/__tests__/MultiSelect.spec.tsx
  packages/strapi-design-system/src/Select/__tests__/MultiSelectNested.spec.tsx
  packages/strapi-design-system/src/Select/__tests__/SingleSelect.spec.tsx
Labels: pr: fix, source: design-system

#1192 [release]: 1.8.2
  .github/workflows/experimental.yml
  .github/workflows/tests.yml
  docs/stories/ToggleCheckbox.stories.mdx
  docs/stories/ToggleInput.stories.mdx
  lerna.json
  package.json
  packages/primitives/package.json
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/Combobox/Combobox.tsx
  packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx
  packages/strapi-design-system/src/DatePicker/DatePicker.tsx
  packages/strapi-design-system/src/Popover/Popover.tsx
  packages/strapi-design-system/src/Select/MultiSelect.tsx
  packages/strapi-design-system/src/Select/MultiSelectNested.tsx
  packages/strapi-design-system/src/Select/SingleSelect.tsx
  packages/strapi-design-system/src/Select/__tests__/MultiSelect.spec.tsx
  packages/strapi-design-system/src/Select/__tests__/MultiSelectNested.spec.tsx
  packages/strapi-design-system/src/Select/__tests__/SingleSelect.spec.tsx
  packages/strapi-design-system/src/ToggleInput/ToggleInput.tsx
  packages/strapi-design-system/src/ToggleInput/__tests__/ToggleInput.e2e.ts
  packages/strapi-design-system/src/ToggleInput/__tests__/ToggleInput.spec.tsx
  packages/strapi-design-system/src/Typography/Typography.tsx
  packages/strapi-design-system/src/Typography/utils.ts
  packages/strapi-icons/package.json
  yarn.lock
Labels: source: release, pr: release

#1197 chore: update design system contributing docs
  CONTRIBUTING.md
Labels: pr: doc, source: design-system
