Repository strapi/design-system, pull requests merged in 2023-04, with the labels that each got.

#954 Fixes issue with date picker icon not being visible in dark mode
  packages/strapi-design-system/src/DatePicker/DatePicker.tsx
Labels: pr: fix

#959 Update yarn link docs
  CONTRIBUTING.md
Labels: pr: doc

#961 Fix tests
  packages/primitives/src/components/Select/Select.tsx
  packages/strapi-design-system/src/Combobox/__tests__/Combobox.e2e.ts
  packages/strapi-design-system/src/Select/__tests__/MultiSelect.spec.tsx
  packages/strapi-design-system/src/Select/__tests__/MultiSelectNested.spec.tsx
  packages/strapi-design-system/src/Select/__tests__/Select.e2e.ts
Labels: pr: fix

#958 Remove z-index causing navbar overlap in the CMS
  packages/strapi-design-system/src/Layout/HeaderLayout.js
  packages/strapi-design-system/src/Popover/Popover.tsx
  packages/strapi-design-system/src/Popover/__tests__/Popover.spec.tsx
Labels: pr: fix

#965 fix: only use a span on the placeholder text
  packages/primitives/src/components/Select/Select.tsx
Labels: pr: fix

#966 Select / Combobox refinements
  packages/primitives/src/components/Combobox/Combobox.tsx
  packages/primitives/src/components/Combobox/__tests__/index.test.tsx
  packages/primitives/src/components/Select/Select.tsx
  packages/strapi-design-system/src/Combobox/Combobox.tsx
  packages/strapi-design-system/src/Select/MultiSelect.tsx
  packages/strapi-design-system/src/Select/SelectParts.tsx
Labels: pr: fix

#962 Move to Yarn3 & Update minor deps
  .github/actions/install-modules/action.yml
  .github/actions/install-modules/script.sh
  .github/workflows/bundle-size.yml
  .github/workflows/tests.yml
  .gitignore
  .prettierignore
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  CONTRIBUTING.md
  docs/package.json
  package.json
  packages/primitives/package.json
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/NumberInput/__tests__/NumberInput.e2e.js
  yarn.lock
Labels: pr: chore

#963 Update major deps
  .husky/pre-commit
  docs/package.json
  package.json
  packages/primitives/package.json
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/Select/SelectList.tsx
  packages/strapi-icons/package.json
  yarn.lock
Labels: pr: chore

#968 Refactor DismissibleLayer & Portal
  docs/stories/DismissibleLayer.stories.mdx
  docs/stories/Portal.stories.mdx
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/DismissibleLayer/DismissibleLayer.js
  packages/strapi-design-system/src/DismissibleLayer/__test__/DimissibleLayer.spec.js
  packages/strapi-design-system/src/DismissibleLayer/index.js
  packages/strapi-design-system/src/DismissibleLayer/index.ts
  packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
  packages/strapi-design-system/src/Popover/__tests__/Popover.spec.tsx
  packages/strapi-design-system/src/Portal/Portal.tsx
  packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.tsx
  yarn.lock
Labels: pr: chore

#964 Update to react18 internally & allow in peer-deps
  docs/package.json
  package.json
  packages/primitives/package.json
  packages/primitives/src/components/Select/Select.tsx
  packages/strapi-design-system/package.json
  packages/strapi-design-system/src/Combobox/Combobox.tsx
  packages/strapi-design-system/src/Popover/Popover.tsx
  packages/strapi-design-system/src/Select/MultiSelect.tsx
  packages/strapi-design-system/src/Select/SelectParts.tsx
  packages/strapi-design-system/src/Select/SingleSelect.tsx
  packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.tsx
  packages/strapi-design-system/src/hooks/__tests__/useId.spec.tsx
  packages/strapi-design-system/src/hooks/useIntersection.ts
  packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.tsx
  packages/strapi-icons/package.json
  yarn.lock
Labels: pr: chore

#971 Infer the `multi` prop on `Option` based on the value passed to `Select`
  packages/strapi-design-system/src/Select/Option.tsx
  packages/strapi-design-system/src/Select/Select.tsx
  packages/strapi-design-system/src/Select/__tests__/Select.spec.tsx
Labels: pr: fix
